package com.jobtracker.jobtracker_app.exceptions;

import com.jobtracker.jobtracker_app.utils.MessageKeys;
import org.springframework.http.HttpStatus;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ErrorCode {
    UNCATEGORIZED_ERROR(MessageKeys.UNCATEGORIZED_ERROR, HttpStatus.INTERNAL_SERVER_ERROR),
    INVALID_INPUT(MessageKeys.INVALID_INPUT, HttpStatus.BAD_REQUEST),
    USER_NOT_EXISTED(MessageKeys.USER_NOT_EXISTED, HttpStatus.NOT_FOUND),
    USER_EXISTED(MessageKeys.USER_EXISTED, HttpStatus.BAD_REQUEST),
    ROLE_NOT_EXISTED(MessageKeys.ROLE_NOT_EXISTED, HttpStatus.NOT_FOUND),
    PERMISSION_NOT_EXISTED(MessageKeys.PERMISSION_NOT_EXISTED, HttpStatus.NOT_FOUND),
    ROLE_NOT_ACTIVE(MessageKeys.ROLE_NOT_ACTIVE, HttpStatus.BAD_REQUEST),
    PERMISSION_NOT_ACTIVE(MessageKeys.PERMISSION_NOT_ACTIVE, HttpStatus.BAD_REQUEST),
    ROLE_PERMISSION_EXISTED(MessageKeys.ROLE_PERMISSION_EXISTED, HttpStatus.BAD_REQUEST),
    FIELD_EXISTED(MessageKeys.FIELD_EXISTED, HttpStatus.BAD_REQUEST),
    NAME_EXISTED(MessageKeys.NAME_EXISTED, HttpStatus.BAD_REQUEST),
    UNAUTHENTICATED(MessageKeys.UNAUTHENTICATED, HttpStatus.UNAUTHORIZED),
    INVALID_TOKEN(MessageKeys.INVALID_TOKEN, HttpStatus.UNAUTHORIZED),
    INCORRECT_CURRENT_PASSWORD(MessageKeys.INCORRECT_CURRENT_PASSWORD, HttpStatus.BAD_REQUEST),
    JOB_STATUS_NOT_EXISTED(MessageKeys.JOB_STATUS_NOT_EXISTED, HttpStatus.NOT_FOUND),
    JOB_TYPE_NOT_EXISTED(MessageKeys.JOB_TYPE_NOT_EXISTED, HttpStatus.NOT_FOUND),
    PRIORITY_NOT_EXISTED(MessageKeys.PRIORITY_NOT_EXISTED, HttpStatus.NOT_FOUND),
    EXPERIENCE_LEVEL_NOT_EXISTED(MessageKeys.EXPERIENCE_LEVEL_NOT_EXISTED, HttpStatus.NOT_FOUND),
    INTERVIEW_TYPE_NOT_EXISTED(MessageKeys.INTERVIEW_TYPE_NOT_EXISTED, HttpStatus.NOT_FOUND),
    INTERVIEW_STATUS_NOT_EXISTED(MessageKeys.INTERVIEW_STATUS_NOT_EXISTED, HttpStatus.NOT_FOUND),
    INTERVIEW_RESULT_NOT_EXISTED(MessageKeys.INTERVIEW_RESULT_NOT_EXISTED, HttpStatus.NOT_FOUND),
    NOTIFICATION_TYPE_NOT_EXISTED(MessageKeys.NOTIFICATION_TYPE_NOT_EXISTED, HttpStatus.NOT_FOUND),
    NOTIFICATION_PRIORITY_NOT_EXISTED(MessageKeys.NOTIFICATION_PRIORITY_NOT_EXISTED, HttpStatus.NOT_FOUND),
    COMPANY_NOT_EXISTED(MessageKeys.COMPANY_NOT_EXISTED, HttpStatus.NOT_FOUND),
    SKILL_NOT_EXISTED(MessageKeys.SKILL_NOT_EXISTED, HttpStatus.NOT_FOUND),
    JOB_NOT_EXISTED(MessageKeys.JOB_NOT_EXISTED, HttpStatus.NOT_FOUND),
    JOB_SKILL_NOT_EXISTED(MessageKeys.JOB_SKILL_NOT_EXISTED, HttpStatus.NOT_FOUND),
    JOB_SKILL_EXISTED(MessageKeys.JOB_SKILL_EXISTED, HttpStatus.BAD_REQUEST),
    USER_SKILL_NOT_EXISTED(MessageKeys.USER_SKILL_NOT_EXISTED, HttpStatus.NOT_FOUND),
    INTERVIEW_NOT_EXISTED(MessageKeys.INTERVIEW_NOT_EXISTED, HttpStatus.NOT_FOUND),
    APPLICATION_NOT_EXISTED(MessageKeys.APPLICATION_NOT_EXISTED, HttpStatus.NOT_FOUND),
    APPLICATION_STATUS_NOT_EXISTED(MessageKeys.APPLICATION_STATUS_NOT_EXISTED, HttpStatus.NOT_FOUND),
    JOB_RESUME_NOT_EXISTED(MessageKeys.JOB_RESUME_NOT_EXISTED, HttpStatus.NOT_FOUND),
    RESUME_NOT_EXISTED(MessageKeys.RESUME_NOT_EXISTED, HttpStatus.NOT_FOUND),
    ATTACHMENT_NOT_EXISTED(MessageKeys.ATTACHMENT_NOT_EXISTED, HttpStatus.NOT_FOUND),
    NOTIFICATION_NOT_EXISTED(MessageKeys.NOTIFICATION_NOT_EXISTED, HttpStatus.NOT_FOUND),
    USER_SESSION_NOT_EXISTED(MessageKeys.USER_SESSION_NOT_EXISTED, HttpStatus.NOT_FOUND),
    AUDIT_LOG_NOT_EXISTED(MessageKeys.AUDIT_LOG_NOT_EXISTED, HttpStatus.NOT_FOUND),
    SUBSCRIPTION_PLAN_NOT_EXISTED(MessageKeys.SUBSCRIPTION_PLAN_NOT_EXISTED, HttpStatus.NOT_FOUND),
    COMPANY_SUBSCRIPTION_NOT_EXISTED(MessageKeys.COMPANY_SUBSCRIPTION_NOT_EXISTED, HttpStatus.NOT_FOUND),
    PAYMENT_NOT_EXISTED(MessageKeys.PAYMENT_NOT_EXISTED, HttpStatus.NOT_FOUND),

    UPLOAD_FILE_FAILED(MessageKeys.UPLOAD_FILE_FAILED, HttpStatus.INTERNAL_SERVER_ERROR),
    DELETE_FILE_FAILED(MessageKeys.DELETE_FILE_FAILED, HttpStatus.INTERNAL_SERVER_ERROR);

    private final String message;
    private final HttpStatus httpStatus;
}
